# -*- coding: utf-8 -*-
"""Internetspeedtest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9rEE98ZrEUKZaD2Ryjw88SskBjSqwuO
"""

!pip install speedtest-cli

import speedtest

def internet_speed_test():
    st = speedtest.Speedtest()
    st.get_best_server()

    download_speed = st.download() / 1_000_000  # Convert to Mbps
    upload_speed = st.upload() / 1_000_000      # Convert to Mbps
    ping = st.results.ping

    print("\n--- Google Colab Internet Speed Test ---")
    print(f"Download Speed: {download_speed:.2f} Mbps")
    print(f"Upload Speed: {upload_speed:.2f} Mbps")
    print(f"Ping: {ping} ms")

internet_speed_test()